INTERVENTIONS = [
    "Plant 100 olive trees in semi-arid zones",
    "Install 10 solar-powered irrigation systems",
    "Construct 3 wetland buffer zones",
    "Replace 50 diesel pumps with solar pumps",
    "Implement drip irrigation across 50 hectares",
    "Establish 20 small-scale wastewater reuse units",
    "Deploy 100 organic compost pits",
    "Reforest 200 hectares with native shrubs",
    "Train 200 farmers in precision agriculture",
    "Build 5 sediment control dams",
    "Upgrade 15 km of irrigation canals",
    "Install 30 biogas digesters for farms",
    "Construct 10 agroforestry demo plots",
    "Harvest 1000 m3 rainwater storage capacity",
    "Distribute 200 water-saving household kits",
    "Construct 4 fish-friendly irrigation diversions",
    "Create 10 community seed banks",
    "Introduce rotational grazing for 500 livestock",
    "Deploy 50 smart soil sensors",
    "Install 25 efficient cookstoves",
    "Build 20 beekeeping units",
    "Restore 300 meters of riverbanks",
    "Introduce 10 greywater recycling systems",
    "Train 100 youth in solar panel maintenance",
    "Convert 50 hectares to permaculture systems",
    "Establish 5 ecosystem monitoring stations",
    "Apply organic mulching on 70 hectares",
    "Install floating wetlands in 3 reservoirs",
    "Set up 5 digital water usage monitoring units",
    "Build 8 stormwater infiltration trenches",
    "Introduce drought-tolerant seed varieties",
    "Conduct 15 workshops on ecosystem conservation",
    "Replace 100 streetlights with solar lamps",
    "Train 300 farmers on climate-smart agriculture",
    "Plant 10,000 mangrove saplings",
    "Set up real-time groundwater monitoring sensors",
    "Create 5 artificial aquifer recharge zones",
    "Train 50 community leaders on WEFE Nexus",
    "Construct 3 solar-powered desalination units"
]
